[package]
name = "loadtxt"
version = "0.1.0"
authors = ["Ben Kimock <kimockb@gmail.com>"]
edition = "2018"

[dependencies]
num_cpus = "1.9"
scoped_threadpool = "0.1.9"
lexical = "1.9"

[lib]
crate-type = ["cdylib"]
